### ISSUE TITLE
force use UTF-8 encode for transmission

### ISSUE THREAD

**Issue by FallenCrystal** [SawFowl/CommandSync#30] opened 2022-12-18 06:14 UTC
the windows force the use of GB2312(chinese). when im sync command includes Chinese or symbols. the result was the <?> of UTF-8

**Comment by SawFowl** [comment] 2022-12-19 05:18
Use the command line argument `-Dfile.encoding=UTF-8` when starting the server. If that does not help you should switch to Linux and then you will forget about such problems like a bad dream.
As you can see, the plugin repository already has support for the Chinese language.

**Comment by FallenCrystal** [comment] 2022-12-19 05:25
doing so on a 1.8 server will result in unreadable consoles.

**Comment by SawFowl** [comment] 2022-12-19 05:27
I can only recommend that you switch to Linux. I am not going to fix the Microsoft bugs.

**Comment by FallenCrystal** [comment] 2022-12-19 05:32
is there no one way to transfer according to the encoding of the console? if yes. i'll look for something else. i use my server as if it were my workstation. not just minecraft. i thought about linux. but it take much time on migrating my work.
if it cant be fixed. then i'll try to find something else.

**Comment by SawFowl** [comment] 2022-12-19 05:38
It can't be fixed without creating other problems.  You need to specify UTF-8 encoding at server startup for normal Unicode display.  An alternative is to change the encoding of the localization file, you can do it yourself via Notepad++.  However, in this case I cannot guarantee that everything will be displayed correctly. If you want a normal game server without the problems caused by Microsoft, there is only one way to go: running it on Linux. You can also try WSL 2.

**Closed as not planned** 2023-03-27 11:40 UTC
